# Generated by Django 5.1.3 on 2024-11-25 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0005_alter_fornecedor_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={},
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['cnpj'], name='fornecedor__cnpj_2b52ef_idx'),
        ),
    ]
