# Generated by Django 5.1.1 on 2024-10-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_itempedido_options_alter_pedido_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedido'},
        ),
    ]
