# Generated by Django 5.1.1 on 2024-10-05 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cliente.cliente')),
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('prazo_entrega_dias', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
            bases=('cliente.cliente',),
        ),
    ]
