# Generated by Django 4.1 on 2024-11-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='numero',
            field=models.PositiveBigIntegerField(max_length=5),
        ),
    ]
