# Generated by Django 5.1.1 on 2024-10-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='email_2',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='email_1',
        ),
    ]
