# Generated by Django 5.1.1 on 2024-10-05 19:19

import django.core.validators
import django.db.models.deletion
import utils.validatorcnpj
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=7)),
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[utils.validatorcnpj.validate_cnpj])),
                ('ie', models.CharField(blank=True, max_length=20, null=True)),
                ('im', models.CharField(blank=True, max_length=20, null=True)),
                ('contato', models.CharField(max_length=255)),
                ('email_1', models.EmailField(max_length=255)),
                ('email_2', models.EmailField(blank=True, max_length=255, null=True)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato XXXXX-XXX', regex='^\\d{5}-\\d{3}$')])),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('usuario', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
