# Generated by Django 5.1.1 on 2024-10-02 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='pais',
        ),
    ]
