# Generated by Django 5.1.1 on 2024-10-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_alter_cliente_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='observacao',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
