# Generated by Django 5.1.1 on 2024-10-01 01:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('nome', models.CharField(max_length=255)),
                ('login', models.EmailField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('nivel_acesso', models.IntegerField()),
            ],
        ),
    ]
