# Generated by Django 5.1.1 on 2024-10-16 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', 'Selecione o status'), ('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=7)),
                ('nome', models.CharField(max_length=255)),
                ('login', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('nivel_acesso', models.CharField(choices=[('', 'Selecione o acesso'), ('administrador', 'Administrador'), ('gerente', 'Gerente'), ('funcionario', 'Funcionário')], max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('deve_redefinir_senha', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
