# Generated by Django 5.1.1 on 2024-10-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('', 'Selecione o acesso'), ('administrador', 'Administrador'), ('gerente', 'Gerente'), ('funcionario', 'Funcionário')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('', 'Selecione o status'), ('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=7),
        ),
    ]
