# Generated by Django 5.1.1 on 2024-10-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('funcionario', 'Funcionário')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=7),
        ),
    ]
