# Generated by Django 5.1.1 on 2024-10-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_cpf_alter_usuario_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rg',
        ),
    ]
