# Generated by Django 5.1.1 on 2024-10-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_cpf_remove_usuario_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='deve_redefinir_senha',
            field=models.BooleanField(default=False),
        ),
    ]
