# Generated by Django 5.1.1 on 2024-10-06 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('status', models.CharField(choices=[('', 'Selecione o status'), ('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=7)),
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('', 'Selecione a categoria'), ('Hortaliça de Flor', 'Hortaliça de Flor'), ('Hortaliça de Folha', 'Hortaliça de Folha'), ('Tubérculo', 'Tubérculo')], max_length=255)),
                ('grupo', models.CharField(blank=True, max_length=255)),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('iluminacao', models.FloatField()),
                ('crescimento', models.FloatField()),
                ('intensidade_led', models.FloatField()),
                ('nivel_agua', models.FloatField()),
                ('solucao_nutritiva', models.TextField(max_length=255)),
                ('observacao', models.TextField(blank=True, max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor')),
                ('usuario', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
