# Generated by Django 5.1.1 on 2024-10-19 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('HORTALICA_DE_FLOR', 'Hortaliça de Flor'), ('HORTALICA_DE_FOLHA', 'Hortaliça de Folha'), ('TUBERCULO', 'Tubérculo')], max_length=255)),
                ('grupo', models.CharField(blank=True, max_length=255)),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('iluminacao', models.FloatField()),
                ('crescimento', models.IntegerField()),
                ('intensidade_led', models.FloatField()),
                ('nivel_agua', models.FloatField()),
                ('solucao_nutritiva', models.TextField()),
                ('observacao', models.TextField(blank=True, max_length=255)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
