# Generated by Django 5.1.1 on 2024-10-06 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('produto', '0002_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('', 'Selecione a categoria'), ('Hortaliça de Flor', 'Hortaliça de Flor'), ('Hortaliça de Folha', 'Hortaliça de Folha'), ('Tubérculo', 'Tubérculo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor'),
        ),
    ]
