# Generated by Django 5.1.1 on 2024-10-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_solucao_nutritiva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('HORTALICA_DE_FLOR', 'Hortaliça de Flor'), ('HORTALICA_DE_FOLHA', 'Hortaliça de Folha'), ('TUBERCULO', 'Tubérculo')], max_length=255),
        ),
    ]
