# Generated by Django 5.1.1 on 2024-10-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_observacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
