# Generated by Django 5.1.1 on 2024-10-06 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('produto', '0003_alter_produto_categoria_alter_produto_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor'),
        ),
    ]
