# Generated by Django 5.1.1 on 2024-10-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Hortaliça de Flor', 'Hortaliça de Flor'), ('Hortaliça de Folha', 'Hortaliça de Folha'), ('Tubérculo', 'Tubérculo')], max_length=255),
        ),
    ]
