# Generated by Django 5.1.1 on 2024-10-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='observacao',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
