# Generated by Django 5.1.1 on 2024-10-06 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioFuncionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=10)),
                ('orgao_emissor', models.CharField(max_length=10)),
                ('contato', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('data_admissao', models.DateField()),
                ('data_cadastro', models.DateTimeField()),
                ('logradouro', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=5)),
                ('cep', models.CharField(max_length=9)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('usuario', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
