# Generated by Django 5.1.1 on 2024-10-16 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_relatorio', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='funcionario.funcionario')),
            ],
            options={
                'verbose_name': 'Relatório de Funcionário',
                'verbose_name_plural': 'Relatório de Funcionários',
            },
        ),
    ]
