# Generated by Django 5.1.1 on 2024-10-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
        ('relatorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_relatorio', models.DateTimeField(auto_now_add=True)),
                ('producao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='producao.producao')),
            ],
            options={
                'verbose_name': 'Relatório de Produção',
                'verbose_name_plural': 'Relatórios de Produção',
            },
        ),
    ]
