# Generated by Django 5.1.3 on 2024-11-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0006_alter_fornecedor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.RemoveIndex(
            model_name='fornecedor',
            name='fornecedor__cnpj_2b52ef_idx',
        ),
    ]
