# Generated by Django 5.1.1 on 2024-10-26 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EM_PLANEJAMENTO', 'Em planejamento'), ('EM_PRODUCAO', 'Em produção'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='Em planejamento', max_length=20)),
                ('prazo_entrega', models.DateField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('controle_ambiente', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to='pedido.pedido')),
            ],
            options={
                'verbose_name': 'Produção',
                'verbose_name_plural': 'Produções',
            },
        ),
    ]
