# Generated by Django 5.1.1 on 2024-10-26 20:42

import django.core.validators
import utils.validatorcpf
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(choices=[('AGRONOMO', 'Agrônomo'), ('ANALISTA_DE_RECURSOS_HUMANOS', 'Analista de Recursos Humanos'), ('ANALISTA_DE_SUSTENTABILIDADE', 'Analista de Sustentabilidade'), ('ASSISTENTE_ADMINISTRATIVO', 'Assistente Administrativo'), ('AUXILIAR_DE_LIMPEZA_E_MANUTENCAO', 'Auxiliar de Limpeza e Manutenção'), ('AUXILIAR_DE_PRODUCAO_AGRICOLA', 'Auxiliar de Produção Agrícola'), ('ENGENHEIRO_AGRONOMO', 'Engenheiro Agrônomo'), ('ESPECIALISTA_EM_HIDROPONIA', 'Especialista em Hidroponia'), ('GERENTE_DE_PRODUCAO_AGRICOLA', 'Gerente de Produção Agrícola'), ('TECNICO_EM_AGRICULTURA', 'Técnico em Agricultura'), ('TECNICO_EM_MEIO_AMBIENTE', 'Técnico em Meio Ambiente'), ('VENDAS_E_MARKETING', 'Vendas e Marketing')], max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[utils.validatorcpf.validate_cpf])),
                ('rg', models.CharField(max_length=10)),
                ('orgao_emissor', models.CharField(choices=[('SSP/AC', 'SSP/AC'), ('SSP/AL', 'SSP/AL'), ('SSP/AP', 'SSP/AP'), ('SSP/AM', 'SSP/AM'), ('SSP/BA', 'SSP/BA'), ('SSPDS/CE', 'SSPDS/CE'), ('SSP/DF', 'SSP/DF'), ('SESP/ES', 'SESP/ES'), ('SSP/GO', 'SSP/GO'), ('SSP/MA', 'SSP/MA'), ('SSP/MT', 'SSP/MT'), ('SSP/MS', 'SSP/MS'), ('SSP/MG', 'SSP/MG'), ('SSP/PA', 'SSP/PA'), ('SSP/PB', 'SSP/PB'), ('SSP/PR', 'SSP/PR'), ('SSP/PE', 'SSP/PE'), ('SSP/PI', 'SSP/PI'), ('SSP/RJ', 'SSP/RJ'), ('SESED/RN', 'SESED/RN'), ('SSP/RS', 'SSP/RS'), ('SESDEC/RO', 'SESDEC/RO'), ('SESP/RR', 'SESP/RR'), ('SSP/SC', 'SSP/SC'), ('SSP/SP', 'SSP/SP'), ('SSP/SE', 'SSP/SE'), ('SSP/TO', 'SSP/TO')], default='SSP', max_length=10)),
                ('contato', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('data_admissao', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('logradouro', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=5)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato XXXXX-XXX', regex='^\\d{5}-\\d{3}$')])),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('observacao', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
