# Generated by Django 5.1.1 on 2024-10-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_funcionario_observacao_alter_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('', 'Selecione o cargo'), ('Agrônomo', 'Agrônomo'), ('Analista de Recursos Humanos', 'Analista de Recursos Humanos'), ('Analista de Sustentabilidade', 'Analista de Sustentabilidade'), ('Assistente Administrativo', 'Assistente Administrativo'), ('Auxiliar de Limpeza e Manutenção', 'Auxiliar de Limpeza e Manutenção'), ('Auxiliar de Produção Agrícola', 'Auxiliar de Produção Agrícola'), ('Engenheiro Agrônomo', 'Engenheiro Agrônomo'), ('Especialista em Hidroponia', 'Especialista em Hidroponia'), ('Gerente de Produção Agrícola', 'Gerente de Produção Agrícola'), ('Técnico em Agricultura', 'Técnico em Agricultura'), ('Técnico em Meio Ambiente', 'Técnico em Meio Ambiente'), ('Vendas e Marketing', 'Vendas e Marketing')], max_length=50),
        ),
    ]
