# Generated by Django 5.1.1 on 2024-10-05 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_remove_funcionario_orgao_funcionario_orgao_emissor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
    ]
