# Generated by Django 5.1.1 on 2024-10-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=7),
        ),
    ]
