# Generated by Django 5.1.1 on 2024-10-02 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoVenda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('num_pedido', models.IntegerField()),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Em andamento', max_length=20)),
                ('data_venda', models.DateField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('prazo_entrega', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
