# Generated by Django 5.1.1 on 2024-10-26 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producao.producao'),
        ),
    ]
