# Generated by Django 5.1.1 on 2024-10-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='fornecedor',
        ),
    ]
