# Generated by Django 5.1.1 on 2024-10-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidovenda',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='pedidovenda',
            name='id_venda',
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='num_pedido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
