# Generated by Django 5.1.1 on 2024-10-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
        ('pedido', '0002_remove_itempedido_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='fornecedor',
            field=models.ForeignKey(default=2, editable=False, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor'),
            preserve_default=False,
        ),
    ]
