# Generated by Django 5.1.1 on 2024-10-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_initial'),
        ('fornecedor', '0002_initial'),
        ('pedido', '0003_alter_pedido_cliente'),
        ('producao', '0001_initial'),
        ('produto', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='prazo_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='producao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='Em andamento', max_length=20),
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('descricao', models.CharField(editable=False, max_length=255)),
                ('prazo_entrega', models.DateField(editable=False)),
                ('fornecedor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedido.pedido')),
                ('producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producao.producao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='produto.produto')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
    ]
