# Generated by Django 5.1.1 on 2024-10-28 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_alter_pedido_options_remove_pedido_descricao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
    ]
