# Generated by Django 4.1 on 2024-11-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='status',
            field=models.CharField(choices=[('EM_PLANEJAMENTO', 'Em planejamento'), ('EM_PRODUCAO', 'Em produção'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='EM_PLANEJAMENTO', max_length=20),
        ),
    ]
